quarto:	quarto.c quarto.h win.c
	gcc -Wall -g -o quarto quarto.c win.c -lncurses -lm

clean:	
	@rm -rf quarto.o win.o *~ *.dSYM
	@echo Made clean.

realclean:	clean
	@rm -f quarto
	@echo Really.

love:
	@echo Not war.
